name: ethereum_address
description: A dart library to generate, checksum, and validate Ethereum addresses
version: 1.0.1
homepage: https://github.com/petejkim/dart-ethereum_address

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  convert: ^3.0.0
  pointycastle: ^2.0.1

dev_dependencies:
  test: ^1.9.4
